/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq;


import com.nrapendra.jooq.tables.PermissionTb;
import com.nrapendra.jooq.tables.QuestionTagTb;
import com.nrapendra.jooq.tables.QuestionTb;
import com.nrapendra.jooq.tables.RolePermissionTb;
import com.nrapendra.jooq.tables.RoleTb;
import com.nrapendra.jooq.tables.TagTb;
import com.nrapendra.jooq.tables.UserRoleTb;
import com.nrapendra.jooq.tables.UserTb;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AiQaSystem extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ai_qa_system</code>
     */
    public static final AiQaSystem AI_QA_SYSTEM = new AiQaSystem();

    /**
     * 题目表
     */
    public final QuestionTb QA_QUESTION = QuestionTb.QA_QUESTION;

    /**
     * 题目标签关联表
     */
    public final QuestionTagTb QA_QUESTION_TAG = QuestionTagTb.QA_QUESTION_TAG;

    /**
     * 标签表
     */
    public final TagTb QA_TAG = TagTb.QA_TAG;

    /**
     * 权限表
     */
    public final PermissionTb SYS_PERMISSION = PermissionTb.SYS_PERMISSION;

    /**
     * 角色表
     */
    public final RoleTb SYS_ROLE = RoleTb.SYS_ROLE;

    /**
     * 角色权限关联表
     */
    public final RolePermissionTb SYS_ROLE_PERMISSION = RolePermissionTb.SYS_ROLE_PERMISSION;

    /**
     * 用户表
     */
    public final UserTb SYS_USER = UserTb.SYS_USER;

    /**
     * 用户角色关联表
     */
    public final UserRoleTb SYS_USER_ROLE = UserRoleTb.SYS_USER_ROLE;

    /**
     * No further instances allowed
     */
    private AiQaSystem() {
        super("ai_qa_system", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            QuestionTb.QA_QUESTION,
            QuestionTagTb.QA_QUESTION_TAG,
            TagTb.QA_TAG,
            PermissionTb.SYS_PERMISSION,
            RoleTb.SYS_ROLE,
            RolePermissionTb.SYS_ROLE_PERMISSION,
            UserTb.SYS_USER,
            UserRoleTb.SYS_USER_ROLE
        );
    }
}
