/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq;


import com.nrapendra.jooq.tables.QuestionTagTb;
import com.nrapendra.jooq.tables.QuestionTb;
import com.nrapendra.jooq.tables.TagTb;
import com.nrapendra.jooq.tables.UserRoleTb;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in ai_qa_system.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index QA_QUESTION_IDX_CREATOR_USER_ID = Internal.createIndex(DSL.name("idx_creator_user_id"), QuestionTb.QA_QUESTION, new OrderField[] { QuestionTb.QA_QUESTION.CREATOR }, false);
    public static final Index QA_QUESTION_IDX_DIFFICULTY_LEVEL = Internal.createIndex(DSL.name("idx_difficulty_level"), QuestionTb.QA_QUESTION, new OrderField[] { QuestionTb.QA_QUESTION.DIFFICULTY }, false);
    public static final Index QA_TAG_IDX_PARENT_TAG_ID = Internal.createIndex(DSL.name("idx_parent_tag_id"), TagTb.QA_TAG, new OrderField[] { TagTb.QA_TAG.PARENT_TAG_ID }, false);
    public static final Index SYS_USER_ROLE_IDX_ROLE_ID = Internal.createIndex(DSL.name("idx_role_id"), UserRoleTb.SYS_USER_ROLE, new OrderField[] { UserRoleTb.SYS_USER_ROLE.ROLE_ID }, false);
    public static final Index QA_QUESTION_TAG_IDX_TAG_ID = Internal.createIndex(DSL.name("idx_tag_id"), QuestionTagTb.QA_QUESTION_TAG, new OrderField[] { QuestionTagTb.QA_QUESTION_TAG.TAG_ID }, false);
    public static final Index SYS_USER_ROLE_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), UserRoleTb.SYS_USER_ROLE, new OrderField[] { UserRoleTb.SYS_USER_ROLE.USERNAME }, false);
}
