/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq;


import com.nrapendra.jooq.tables.UserRoleTb;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in ai_qa_system.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index SYS_USER_ROLE_IDX_ROLE_ID = Internal.createIndex(DSL.name("idx_role_id"), UserRoleTb.SYS_USER_ROLE, new OrderField[] { UserRoleTb.SYS_USER_ROLE.ROLE_ID }, false);
    public static final Index SYS_USER_ROLE_IDX_USERNAME = Internal.createIndex(DSL.name("idx_username"), UserRoleTb.SYS_USER_ROLE, new OrderField[] { UserRoleTb.SYS_USER_ROLE.USERNAME }, false);
}
