/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq;


import com.nrapendra.jooq.tables.AnswerTb;
import com.nrapendra.jooq.tables.CategoryTb;
import com.nrapendra.jooq.tables.MappingTb;
import com.nrapendra.jooq.tables.NotificationTb;
import com.nrapendra.jooq.tables.OperationLogTb;
import com.nrapendra.jooq.tables.PermissionTb;
import com.nrapendra.jooq.tables.QuestionFavoriteTb;
import com.nrapendra.jooq.tables.QuestionHistoryTb;
import com.nrapendra.jooq.tables.QuestionTb;
import com.nrapendra.jooq.tables.RolePermissionTb;
import com.nrapendra.jooq.tables.RoleTb;
import com.nrapendra.jooq.tables.TagTb;
import com.nrapendra.jooq.tables.UserRoleTb;
import com.nrapendra.jooq.tables.UserTb;


/**
 * Convenience access to all tables in ai_qa_system.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 题目答案表
     */
    public static final AnswerTb QA_ANSWER = AnswerTb.QA_ANSWER;

    /**
     * 题目分类表
     */
    public static final CategoryTb QA_CATEGORY = CategoryTb.QA_CATEGORY;

    /**
     * 题目标签关联表
     */
    public static final MappingTb QA_MAPPING = MappingTb.QA_MAPPING;

    /**
     * 题目表
     */
    public static final QuestionTb QA_QUESTION = QuestionTb.QA_QUESTION;

    /**
     * 题目收藏表
     */
    public static final QuestionFavoriteTb QA_QUESTION_FAVORITE = QuestionFavoriteTb.QA_QUESTION_FAVORITE;

    /**
     * 题目历史记录表
     */
    public static final QuestionHistoryTb QA_QUESTION_HISTORY = QuestionHistoryTb.QA_QUESTION_HISTORY;

    /**
     * 标签表
     */
    public static final TagTb QA_TAG = TagTb.QA_TAG;

    /**
     * The table <code>ai_qa_system.sys_notification</code>.
     */
    public static final NotificationTb SYS_NOTIFICATION = NotificationTb.SYS_NOTIFICATION;

    /**
     * The table <code>ai_qa_system.sys_operation_log</code>.
     */
    public static final OperationLogTb SYS_OPERATION_LOG = OperationLogTb.SYS_OPERATION_LOG;

    /**
     * 权限表
     */
    public static final PermissionTb SYS_PERMISSION = PermissionTb.SYS_PERMISSION;

    /**
     * 角色表
     */
    public static final RoleTb SYS_ROLE = RoleTb.SYS_ROLE;

    /**
     * 角色权限关联表
     */
    public static final RolePermissionTb SYS_ROLE_PERMISSION = RolePermissionTb.SYS_ROLE_PERMISSION;

    /**
     * 用户表
     */
    public static final UserTb SYS_USER = UserTb.SYS_USER;

    /**
     * 用户角色关联表
     */
    public static final UserRoleTb SYS_USER_ROLE = UserRoleTb.SYS_USER_ROLE;
}
