/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables;


import com.nrapendra.jooq.AiQaSystem;
import com.nrapendra.jooq.Indexes;
import com.nrapendra.jooq.Keys;
import com.nrapendra.jooq.tables.records.TagRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * 标签表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTb extends TableImpl<TagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ai_qa_system.qa_tag</code>
     */
    public static final TagTb QA_TAG = new TagTb();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TagRecord> getRecordType() {
        return TagRecord.class;
    }

    /**
     * The column <code>ai_qa_system.qa_tag.tag_id</code>. 标签ID
     */
    public final TableField<TagRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "标签ID");

    /**
     * The column <code>ai_qa_system.qa_tag.tag_name</code>. 标签名称
     */
    public final TableField<TagRecord, String> TAG_NAME = createField(DSL.name("tag_name"), SQLDataType.VARCHAR(50).nullable(false), this, "标签名称");

    /**
     * The column <code>ai_qa_system.qa_tag.parent_tag_id</code>. 父标签ID
     */
    public final TableField<TagRecord, Long> PARENT_TAG_ID = createField(DSL.name("parent_tag_id"), SQLDataType.BIGINT, this, "父标签ID");

    /**
     * The column <code>ai_qa_system.qa_tag.tag_level</code>. 标签层级 1:一级标签 2:二级标签
     */
    public final TableField<TagRecord, UByte> TAG_LEVEL = createField(DSL.name("tag_level"), SQLDataType.TINYINTUNSIGNED.nullable(false), this, "标签层级 1:一级标签 2:二级标签");

    /**
     * The column <code>ai_qa_system.qa_tag.tag_sort</code>. 排序号
     */
    public final TableField<TagRecord, UInteger> TAG_SORT = createField(DSL.name("tag_sort"), SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(DSL.inline("0", SQLDataType.INTEGERUNSIGNED)), this, "排序号");

    /**
     * The column <code>ai_qa_system.qa_tag.tag_status</code>. 状态 1:正常 0:禁用
     */
    public final TableField<TagRecord, UByte> TAG_STATUS = createField(DSL.name("tag_status"), SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(DSL.inline("1", SQLDataType.TINYINTUNSIGNED)), this, "状态 1:正常 0:禁用");

    /**
     * The column <code>ai_qa_system.qa_tag.create_time</code>. 创建时间
     */
    public final TableField<TagRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>ai_qa_system.qa_tag.update_time</code>. 修改时间
     */
    public final TableField<TagRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "修改时间");

    /**
     * The column <code>ai_qa_system.qa_tag.creator</code>. 创建者
     */
    public final TableField<TagRecord, String> CREATOR = createField(DSL.name("creator"), SQLDataType.VARCHAR(255), this, "创建者");

    private TagTb(Name alias, Table<TagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TagTb(Name alias, Table<TagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("标签表"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>ai_qa_system.qa_tag</code> table reference
     */
    public TagTb(String alias) {
        this(DSL.name(alias), QA_TAG);
    }

    /**
     * Create an aliased <code>ai_qa_system.qa_tag</code> table reference
     */
    public TagTb(Name alias) {
        this(alias, QA_TAG);
    }

    /**
     * Create a <code>ai_qa_system.qa_tag</code> table reference
     */
    public TagTb() {
        this(DSL.name("qa_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : AiQaSystem.AI_QA_SYSTEM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.QA_TAG_IDX_PARENT_TAG_ID);
    }

    @Override
    public UniqueKey<TagRecord> getPrimaryKey() {
        return Keys.KEY_QA_TAG_PRIMARY;
    }

    @Override
    public List<UniqueKey<TagRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_QA_TAG_UK_TAG_NAME);
    }

    @Override
    public TagTb as(String alias) {
        return new TagTb(DSL.name(alias), this);
    }

    @Override
    public TagTb as(Name alias) {
        return new TagTb(alias, this);
    }

    @Override
    public TagTb as(Table<?> alias) {
        return new TagTb(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTb rename(String name) {
        return new TagTb(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTb rename(Name name) {
        return new TagTb(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TagTb rename(Table<?> name) {
        return new TagTb(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb where(Condition condition) {
        return new TagTb(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagTb where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagTb where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagTb where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TagTb where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TagTb whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
