/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables.records;


import com.nrapendra.jooq.tables.MappingTb;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 题目标签关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MappingRecord extends UpdatableRecordImpl<MappingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ai_qa_system.qa_mapping.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ai_qa_system.qa_mapping.question_id</code>. 题目ID
     */
    public void setQuestionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.question_id</code>. 题目ID
     */
    public Long getQuestionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ai_qa_system.qa_mapping.category_id</code>. 分类ID
     */
    public void setCategoryId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.category_id</code>. 分类ID
     */
    public Long getCategoryId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ai_qa_system.qa_mapping.tag_id</code>. 标签ID
     */
    public void setTagId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.tag_id</code>. 标签ID
     */
    public Long getTagId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>ai_qa_system.qa_mapping.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>ai_qa_system.qa_mapping.update_time</code>. 修改时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ai_qa_system.qa_mapping.update_time</code>. 修改时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MappingRecord
     */
    public MappingRecord() {
        super(MappingTb.QA_MAPPING);
    }

    /**
     * Create a detached, initialised MappingRecord
     */
    public MappingRecord(Long id, Long questionId, Long categoryId, Long tagId, LocalDateTime createTime, LocalDateTime updateTime) {
        super(MappingTb.QA_MAPPING);

        setId(id);
        setQuestionId(questionId);
        setCategoryId(categoryId);
        setTagId(tagId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        resetChangedOnNotNull();
    }
}
