/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables.records;


import com.nrapendra.jooq.tables.OperationLogTb;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperationLogRecord extends UpdatableRecordImpl<OperationLogRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.content</code>. 操作内容
     */
    public void setContent(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.content</code>. 操作内容
     */
    public String getContent() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.method_name</code>. 请求方法
     */
    public void setMethodName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.method_name</code>. 请求方法
     */
    public String getMethodName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.request_params</code>.
     * 请求参数
     */
    public void setRequestParams(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.request_params</code>.
     * 请求参数
     */
    public String getRequestParams() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.operator</code>. 操作者
     */
    public void setOperator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.operator</code>. 操作者
     */
    public String getOperator() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.operation_time</code>.
     * 操作时间
     */
    public void setOperationTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.operation_time</code>.
     * 操作时间
     */
    public LocalDateTime getOperationTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>ai_qa_system.sys_operation_log.time_taken</code>. 耗时
     */
    public void setTimeTaken(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_operation_log.time_taken</code>. 耗时
     */
    public Long getTimeTaken() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperationLogRecord
     */
    public OperationLogRecord() {
        super(OperationLogTb.SYS_OPERATION_LOG);
    }

    /**
     * Create a detached, initialised OperationLogRecord
     */
    public OperationLogRecord(Long id, String content, String methodName, String requestParams, String operator, LocalDateTime operationTime, Long timeTaken) {
        super(OperationLogTb.SYS_OPERATION_LOG);

        setId(id);
        setContent(content);
        setMethodName(methodName);
        setRequestParams(requestParams);
        setOperator(operator);
        setOperationTime(operationTime);
        setTimeTaken(timeTaken);
        resetChangedOnNotNull();
    }
}
