/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables.records;


import com.nrapendra.jooq.tables.RoleTb;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ai_qa_system.sys_role.id</code>. 角色ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.id</code>. 角色ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.name</code>. 角色名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.name</code>. 角色名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.level</code>. 角色级别：0-9，数字越小级别越高
     */
    public void setLevel(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.level</code>. 角色级别：0-9，数字越小级别越高
     */
    public Integer getLevel() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.type</code>. 角色类型：1-内置，2-自定义
     */
    public void setType(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.type</code>. 角色类型：1-内置，2-自定义
     */
    public Integer getType() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(4);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role.creator</code>. 创建者
     */
    public void setCreator(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role.creator</code>. 创建者
     */
    public String getCreator() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(RoleTb.SYS_ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(Long id, String name, Integer level, Integer type, String remark, LocalDateTime createTime, LocalDateTime updateTime, String creator) {
        super(RoleTb.SYS_ROLE);

        setId(id);
        setName(name);
        setLevel(level);
        setType(type);
        setRemark(remark);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setCreator(creator);
        resetChangedOnNotNull();
    }
}
