/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables.records;


import com.nrapendra.jooq.tables.RolePermissionTb;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 角色权限关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RolePermissionRecord extends UpdatableRecordImpl<RolePermissionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ai_qa_system.sys_role_permission.role_id</code>. 角色ID
     */
    public void setRoleId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role_permission.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role_permission.permission_id</code>.
     * 权限ID
     */
    public void setPermissionId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role_permission.permission_id</code>.
     * 权限ID
     */
    public Long getPermissionId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role_permission.create_time</code>.
     * 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role_permission.create_time</code>.
     * 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role_permission.update_time</code>.
     * 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role_permission.update_time</code>.
     * 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>ai_qa_system.sys_role_permission.creator</code>. 创建者
     */
    public void setCreator(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_role_permission.creator</code>. 创建者
     */
    public String getCreator() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RolePermissionRecord
     */
    public RolePermissionRecord() {
        super(RolePermissionTb.SYS_ROLE_PERMISSION);
    }

    /**
     * Create a detached, initialised RolePermissionRecord
     */
    public RolePermissionRecord(Long roleId, Long permissionId, LocalDateTime createTime, LocalDateTime updateTime, String creator) {
        super(RolePermissionTb.SYS_ROLE_PERMISSION);

        setRoleId(roleId);
        setPermissionId(permissionId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setCreator(creator);
        resetChangedOnNotNull();
    }
}
