/*
 * This file is generated by jOOQ.
 */
package com.nrapendra.jooq.tables.records;


import com.nrapendra.jooq.tables.UserRoleTb;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户角色关联表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoleRecord extends UpdatableRecordImpl<UserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ai_qa_system.sys_user_role.id</code>. 主键ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.id</code>. 主键ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>ai_qa_system.sys_user_role.username</code>. 用户名
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.username</code>. 用户名
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ai_qa_system.sys_user_role.role_id</code>. 角色ID
     */
    public void setRoleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.role_id</code>. 角色ID
     */
    public Long getRoleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>ai_qa_system.sys_user_role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>ai_qa_system.sys_user_role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>ai_qa_system.sys_user_role.creator</code>. 创建者
     */
    public void setCreator(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>ai_qa_system.sys_user_role.creator</code>. 创建者
     */
    public String getCreator() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRoleTb.SYS_USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(Long id, String username, Long roleId, LocalDateTime createTime, LocalDateTime updateTime, String creator) {
        super(UserRoleTb.SYS_USER_ROLE);

        setId(id);
        setUsername(username);
        setRoleId(roleId);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
        setCreator(creator);
        resetChangedOnNotNull();
    }
}
